main_path: "/mnt/data/hsf/"
output_path: "/mnt/hsf/models/"
batch_size: 1
num_workers: 16
pin_memory: True
train_ratio: .9
replace: False
k_sample: Null  # i.e. k = train_ratio * num_samples
train_val_test_idx: Null
train_on_all: False

datasets:
  clark:
    path: "hippocampus_clark_3T"
    ca_type: "1/23"
    patterns:
      right_t2:
        mri: "**/t2w_Hippocampus_right_ElasticSyN_crop.nii.gz"
        label: "t2w_Hippocampus_right_ElasticSyN_seg_crop.nii.gz"
      left_t2:
        mri: "**/t2w_Hippocampus_left_ElasticSyN_crop.nii.gz"
        label: "t2w_Hippocampus_left_ElasticSyN_seg_crop.nii.gz"
      averaged_right_t2:
        mri: "**/averaged_t2w_Hippocampus_right_ElasticSyN_crop.nii.gz"
        label: "averaged_t2w_Hippocampus_right_ElasticSyN_seg_crop.nii.gz"
      averaged_left_t2:
        mri: "**/averaged_t2w_Hippocampus_left_ElasticSyN_crop.nii.gz"
        label: "averaged_t2w_Hippocampus_left_ElasticSyN_seg_crop.nii.gz"
    labels:
      1: 1
      2: 2
      3: 3
      4: 4
      5: 5
      6: 6
      7: 7
    labels_names:
      1: "DG"
      2: "CA2/3"
      3: "CA1"
      4: "PRESUB"
      5: "UNCUS"
      6: "PARASUB"
      7: "KYST"
